### ISSUE TITLE
Problem with scanning local HTML files when using Windows agent

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-action#1002]
### Problem
When using `vmImage: "windows-latest"` and following the instructions to [Scan local HTML files](https://github.com/microsoft/accessibility-insights-action/blob/main/docs/ado-extension-usage.md#scan-local-html-files) in the ADO extension, the scan successfully completes but shows incorrect results. Currently the documentation says to use the following configuration: 
```yml
inputs:
      siteDir: '$(System.DefaultWorkingDirectory)/website/root'
      scanUrlRelativePath: '/' # use '//' if Windows agent
```

The logs contain something that looks like:
```
[Trace][info] === Started local web server. Url: http://localhost:5858 Root directory: D:\a\1\s
[Trace][info] === Starting accessibility scanning of URL http://
```
#### More info
The extension is using [url.resolve](https://nodejs.org/api/url.html#urlresolvefrom-to) in `scan-url-resolver.ts`, which may be truncating the url that should be scanned. It appears also that the `url.resolve` method has been deprecated in node v11.0.0 and changed to legacy status in v14.17.0 and v15.13.0.

Note that even though this issue was found when using the ADO extension, it could possibly be an issue in the GitHub Action as well; `scan-url-resolver.ts` is in the `shared` package.

#### Workaround
A workaround for this is to include one trailing `/` to the `siteDir` variable and use just `/` for `scanUrlRelativePath` instead of the documented `//`. So it would look something like the following:
```yml
inputs:
      siteDir: '$(System.DefaultWorkingDirectory)/website/root/'
      scanUrlRelativePath: '/'
```

### Possible solutions
Some options we might consider include:
1. Changing the documentation to specify the configuration suggested in the workaround. Using this configuration seems to work for Linux and macOS agents as well, so there may be no need for system-specific notes.
2. Improving path resolution in `scan-url-resolver.ts` to work for the currently suggested configuration
3. A combination of 1 and 2
4. Other ideas?
