### ISSUE TITLE
Links to images being failed with `html-has-lang` and `image-alt` when scanning local files

### ISSUE THREAD

**Issue by flcdrg** [microsoft/accessibility-insights-action#1151]
## Describe the bug

It seems like when you use the action to scan local files then links to image files are resulting in false positives. 

My guess is that this could be because loading files from a directory does not provide MIME types like they would get if scanning over HTTP, or how the plain images are rendered by the browser.

**To Reproduce**

1. Given a page that has a link to a local image from another image (eg. like a thumbnail image that has a link that lets you load the full image
3. Run the scanner on the original page
4. Notice errors are returned for the URL to the image.

eg.

Calling the action in a workflow like this:
```yaml
      - uses: actions/checkout@v2

      - uses: ./.github/actions/jekyll-build-pages
        with:
          verbose: false

      - run: |
          sudo find -type f ! -regex ".*\.\(html\|svg\|gif\|css\|jpg\|png\)" -delete
        name: Remove non-HTML
        
        # https://github.com/microsoft/accessibility-insights-action
      - name: Scan for accessibility issues
        uses: microsoft/accessibility-insights-action@v2
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            site-dir: ${{ github.workspace }}/_site
            scan-timeout: 6000000
            max-urls: 1500
            localhost-port: 12345
            scan-url-relative-path: /
```

and there's one or more pages that render HTML like this:

```html
<a href="/images/fullimage.png"><img src="thumbnail.png"></a>
```

## Expected behavior

Non-HTML pages should not be scanned

## Screenshots

![image](https://user-images.githubusercontent.com/384747/164816737-5d4d6cf7-3a61-45c8-8b1e-4f9fa1f3dd52.png)
![image](https://user-images.githubusercontent.com/384747/164816887-3e53df7d-f83d-4094-9870-3f51e08f0d44.png)

## Context (please complete the following information)

- OS Name & Version: ubuntu-latest
- AI-Action Version & Environment: v2

## Are you willing to submit a PR?

Depends how easy it would be to fix
