### ISSUE TITLE
ADO extension fails when run in a container:  handleRequestFunction failed, { message: 'read ECONNRESET' }

### ISSUE THREAD

**Issue by katydecorah** [microsoft/accessibility-insights-action#1575]
## Describe the bug

When run in a container, the ADO extension fails with: 

```
 handleRequestFunction failed, reclaiming failed request back to the list or queue
```

It will sometimes includes these additional error messages:
- ` ProtocolError: Protocol error (Target.setAutoAttach): Target closed.`
- `caused by: Error: "{ message: 'read ECONNRESET' }"`

**To Reproduce**

You can reproduce the error by running the extension in a container. https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#single-job

```yaml
pool:
  vmImage: 'windows-2019'

container: mcr.microsoft.com/windows/servercore:ltsc2019

steps:
- script: set

- task: NodeTool@0
  inputs:
      versionSpec: '16.x'

- script: npm install yarn@1.22.10 -g
  displayName: install yarn as a global dependency
    
- task: accessibility-insights.prod.task.accessibility-insights@3
  displayName: '[should fail] staging accessibility insights task against URL with known failures'
  inputs:
    url: 'https://www.washington.edu/accesscomputing/AU/before.html'
```

## Repro example

- https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=42790&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7384d774-f7ca-599c-ee57-ab2c05be9247
- https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=42788&view=logs&j=6b902995-b73d-5f5c-66fd-a7f66c857d2c&t=ff9c4bdf-81d4-57c3-e146-7d6c292d3dad

## Expected behavior

According to [Running Puppeteer in Docker, Troubleshooting](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) there are likely extra steps we should recommend to the user.

It's not clear to me if there's anything we can do on the extension side or if this can be helped with added documentation

## Context (please complete the following information)

- OS Name & Version: 
- Azure DevOps Extension Version & Environment: 
- Browser Version: 
- Target Page: 

## Are you willing to submit a PR?

Yes
