### ISSUE TITLE
Action does not pin the versions of dependencies installed at runtime

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-action#632]
The first step of our composite `action.yml` is currently:

```yaml
        - name: Install npm packages
          run: |
              echo 'Installing npm packages...'
              cd $GITHUB_ACTION_PATH/dist && npm install
              echo 'npm packages successfully installed'
          shell: bash
```

The `npm install` command isn't using a lockfile, which is problematic; it means we (and users) can be broken if any transitive dependency issues a broken update. This is true even if the user pins to a specific version of the action.

Note that converting `dist/package.json` to use non-caret versions is *not* sufficient (that doesn't solve the issue for transitive dependencies).

Easiest solution is probably to copy `yarn.lock` into `/dist/` as part of the build and switch the install step to use `yarn install --frozen-lockfile`, but that might have performance implications; on my machine, this is much much slower than `npm install`. Need to perf test.
